AWSTemplateFormatVersion: 2010-09-09
Description: Create Amazon S3 Bucket
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Create an S3 Bucket with this name
    Properties:
      BucketName: example-bucket-name
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
Outputs:
  S3Bucket:
    Description: Name of S3 Bucket Created
    Value: !Ref S3Bucket
